repos:
-   repo: https://github.com/psf/black.git
    rev: 23.3.0
    hooks:
    -   id: black
        files: (.*\.(py|pyi|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: ["--config=.flake8"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix, --no-cache]